apiVersion: v1
kind: Service
metadata:
  name: jupyterlab
  namespace: jlab
  labels:
    name: jupyterlab
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8888
      protocol: TCP
      name: http
  selector:
    name: jupyterlab
